In [ ]:
# Summarizing and Grouping Data in Pandas

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
import pandas as pd

data = {
    "name": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "department": ["IT", "HR", "IT", "HR", "Finance", "IT", "Finance", "HR"],
    "city": ["BLR", "DEL", "BLR", "DEL", "BLR", "DEL", "BLR", "DEL"],
    "salary": [60000, 50000, 70000, 45000, 80000, 65000, 75000, 48000],
    "experience": [2, 3, 5, 2, 7, 4, 6, 3]
}

df = pd.DataFrame(data)
df

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7
5    F         IT  DEL   65000           4
6    G    Finance  BLR   75000           6
7    H         HR  DEL   48000           3

In [ ]:
# Why Summarize Data?
# 1. To find insights
# 2. Ease of Deicsion making
# 3. Quick overview of data
# 4. Understand the pattern in the data
# 5. Finding trends
# 6. Reduce huge amount of data to meaningful numbers.

In [ ]:
# Descriptive Stats : are methods used to summarize and describe the main features of a dataset.

In [ ]:
df.head() #gives top 5 data by default.

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7

In [ ]:
df.describe() #it gives some insights like count mean std min max

             salary  experience
count      8.000000     8.00000
mean   61625.000000     4.00000
std    13081.475452     1.85164
min    45000.000000     2.00000
25%    49500.000000     2.75000
50%    62500.000000     3.50000
75%    71250.000000     5.25000
max    80000.000000     7.00000

In [ ]:
df.columns  #gives all cols. names..

Index(['name', 'department', 'city', 'salary', 'experience'], dtype='object')

In [ ]:
df['salary'].describe() #gives insights of particular column..

count        8.000000
mean     61625.000000
std      13081.475452
min      45000.000000
25%      49500.000000
50%      62500.000000
75%      71250.000000
max      80000.000000
Name: salary, dtype: float64

In [ ]:
# Quick Aggregations :
print("Mean   Salary = ", df['salary'].mean())
print("Min    Salary = ", df['salary'].min())
print("Max    Salary = ", df['salary'].max())
print("Median Salary = ", df['salary'].median())

Mean   Salary =  61625.0
Min    Salary =  45000
Max    Salary =  80000
Median Salary =  62500.0

In [ ]:
df

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7
5    F         IT  DEL   65000           4
6    G    Finance  BLR   75000           6
7    H         HR  DEL   48000           3

In [ ]:
# Average Salary for Each Dept?
# GroupBy : Group similar rows together, then calculate something for each group.

In [ ]:
# 2 cities, I can create 2dfs, one will contain : blr, other contains : del
# and then i can calc avergae for both

In [ ]:
df

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7
5    F         IT  DEL   65000           4
6    G    Finance  BLR   75000           6
7    H         HR  DEL   48000           3

In [ ]:
df.groupby('city')['salary'].mean() # any aggreation count, min, max, median, etc.

city
BLR    71250.0
DEL    52000.0
Name: salary, dtype: float64

In [ ]:
df.groupby('city')['salary'].max()

city
BLR    80000
DEL    65000
Name: salary, dtype: int64

In [ ]:
df.groupby('city')['salary'].min()

city
BLR    60000
DEL    45000
Name: salary, dtype: int64

In [ ]:
df.head()

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7

In [ ]:
df.groupby('department')['salary'].mean()
# Avg salary for each department!!
# Highest - Finance
# Lowest  - HR

department
Finance    77500.000000
HR         47666.666667
IT         65000.000000
Name: salary, dtype: float64

In [ ]:
df.groupby('department')['salary'].agg(["mean","min","max","median"])
# here we perform all quick aggregation by all.

                    mean    min    max   median
department
Finance     77500.000000  75000  80000  77500.0
HR          47666.666667  45000  50000  48000.0
IT          65000.000000  60000  70000  65000.0

In [ ]:
df

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7
5    F         IT  DEL   65000           4
6    G    Finance  BLR   75000           6
7    H         HR  DEL   48000           3

In [ ]:
df.groupby(['department','city'])['salary'].mean()
  # if we want to do only on particular cols. we can do.. by this

department  city
Finance     BLR     77500.000000
HR          DEL     47666.666667
IT          BLR     65000.000000
            DEL     65000.000000
Name: salary, dtype: float64

In [ ]:
# group by of city, mean - salary and max of exp

df.groupby('city').agg(
    {
        "salary" : "mean",
        "experience" : "max"
    }
)

       salary  experience
city
BLR   71250.0           7
DEL   52000.0           4

In [ ]:
new = df.groupby('city').agg(
    {
        "salary" : "mean",
        "experience" : "mean"
    }
)
new

       salary  experience
city
BLR   71250.0         5.0
DEL   52000.0         3.0

QUESTIONS

In [ ]:
import pandas as pd

# Sample Dataset
data = {
    "name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "department": ["IT", "HR", "IT", "HR", "Finance", "IT", "Finance", "HR", "IT", "Finance"],
    "city": ["BLR", "DEL", "BLR", "DEL", "BLR", "DEL", "BLR", "DEL", "BLR", "DEL"],
    "salary": [60000, 50000, 70000, 45000, 80000, 65000, 75000, 48000, 72000, 82000],
    "experience": [2, 3, 5, 2, 7, 4, 6, 3, 5, 8]
}

df = pd.DataFrame(data)
df

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7
5    F         IT  DEL   65000           4
6    G    Finance  BLR   75000           6
7    H         HR  DEL   48000           3
8    I         IT  BLR   72000           5
9    J    Finance  DEL   82000           8

In [ ]:
# Q1: Find total salary paid per department
df.groupby('department')['salary'].sum()

department
Finance    237000
HR         143000
IT         267000
Name: salary, dtype: int64

In [ ]:
# Q2: Find average experience per city

df.groupby('city')['experience'].mean()

city
BLR    5.0
DEL    4.0
Name: experience, dtype: float64

In [ ]:
# Q3: Find minimum salary in each department

df.groupby('department')['salary'].min()

department
Finance    75000
HR         45000
IT         60000
Name: salary, dtype: int64

In [ ]:
# Q4: Group by department and city → find total salary
df.groupby(['department','city'])['salary'].sum()

department  city
Finance     BLR     155000
            DEL      82000
HR          DEL     143000
IT          BLR     202000
            DEL      65000
Name: salary, dtype: int64

In [ ]:
# Q5: Group by department → find mean salary AND max experience together
df.groupby('department').agg(
    {
        'salary' : 'mean',
        'experience' : 'max'
    }
)

                  salary  experience
department
Finance     79000.000000           8
HR          47666.666667           3
IT          66750.000000           5

In [ ]:
# Pivot Table : & Group by both are same you can use as per your easy.
# pd.pivot_table(df, values=..., index=..., columns=..., aggfunc=...)
# df -> Dataset
# values -> column you want to aggregate
# index -> "department" (grouping level 1)
# column -> creates a matrx (grouping level 2)
# aggfunc -> what you want to do with the values (sum/mean/min/max/median)

In [ ]:
df.head()

  name department city  salary  experience
0    A         IT  BLR   60000           2
1    B         HR  DEL   50000           3
2    C         IT  BLR   70000           5
3    D         HR  DEL   45000           2
4    E    Finance  BLR   80000           7

In [ ]:
# Avg salary for each dept!
pd.pivot_table(df, values = 'salary', index='department', aggfunc='mean')

                  salary
department
Finance     79000.000000
HR          47666.666667
IT          66750.000000

In [ ]:
# Dept vs City salary comparison
pd.pivot_table(df, values = 'salary', index='department', columns='city' ,
               aggfunc='mean')

city                 BLR           DEL
department
Finance     77500.000000  82000.000000
HR                   NaN  47666.666667
IT          67333.333333  65000.000000

In [ ]:
df.groupby(['department','city'])['salary'].mean()
# similar as above

department  city
Finance     BLR     77500.000000
            DEL     82000.000000
HR          DEL     47666.666667
IT          BLR     67333.333333
            DEL     65000.000000
Name: salary, dtype: float64

In [ ]:
# NaN --> missing value

In [ ]:
res = df.groupby(["department", "city"])["salary"].mean()
res

department  city
Finance     BLR     77500.000000
            DEL     82000.000000
HR          DEL     47666.666667
IT          BLR     67333.333333
            DEL     65000.000000
Name: salary, dtype: float64

In [ ]:
res.index # multi-index

MultiIndex([('Finance', 'BLR'),
            ('Finance', 'DEL'),
            (     'HR', 'DEL'),
            (     'IT', 'BLR'),
            (     'IT', 'DEL')],
           names=['department', 'city'])

In [ ]:
res2 = res.reset_index()
res2

  department city        salary
0    Finance  BLR  77500.000000
1    Finance  DEL  82000.000000
2         HR  DEL  47666.666667
3         IT  BLR  67333.333333
4         IT  DEL  65000.000000

In [ ]:
import pandas as pd

# Sample Dataset
data = {
    "item": ["Pen", "Pencil", "Notebook", "Pen", "Notebook", "Pencil", "Pen", "Notebook", "Pencil", "Pen"],
    "store": ["S1", "S1", "S2", "S2", "S1", "S2", "S1", "S2", "S1", "S2"],
    "sales": [100, 50, 200, 120, 180, 60, 130, 220, 70, 140],
    "discount": [10, 5, 20, 15, 10, 5, 12, 18, 7, 14]
}

df = pd.DataFrame(data)
df

# ================= GROUPBY =================

# Q1: Find total sales per item and sort in descending order

# Q2: Find average discount per store and reset index

# Q3: For each item, calculate total sales and maximum discount, then sort by total sales descending

# Q4: Find average sales per item and store, return flat table

# Q5: Count number of transactions per store, sort ascending

# Q6: For each item, find minimum and maximum sales, return as DataFrame

# Q7: Create pivot table → average sales per item

# Q8: Find average discount per store, sort descending, reset index.

       item store  sales  discount
0       Pen    S1    100        10
1    Pencil    S1     50         5
2  Notebook    S2    200        20
3       Pen    S2    120        15
4  Notebook    S1    180        10
5    Pencil    S2     60         5
6       Pen    S1    130        12
7  Notebook    S2    220        18
8    Pencil    S1     70         7
9       Pen    S2    140        14