In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [1, 2, 2, 3, 4, 5, 6],
    "name": ["Alice", "Bob", "Bob", "Charlie", "David", np.nan, "Eve"],
    "age": [25, 30, 30, np.nan, 120, 28, 5],
    "city": ["BLR", "DEL", "DEL", "MUM", "CHE", "BLR", np.nan],
    "amount": [500, 200, 200, 300, 100000, np.nan, 150]
})

df

   customer_id     name    age city    amount
0            1    Alice   25.0  BLR     500.0
1            2      Bob   30.0  DEL     200.0
2            2      Bob   30.0  DEL     200.0
3            3  Charlie    NaN  MUM     300.0
4            4    David  120.0  CHE  100000.0
5            5      NaN   28.0  BLR       NaN
6            6      Eve    5.0  NaN     150.0

In [ ]:
df["amount"].mean()

np.float64(16891.666666666668)

In [ ]:
df["amount"].median()

250.0

In [ ]:
df['age'].sum()

np.float64(238.0)

In [ ]:
len(df['age'])

7

In [ ]:
#mean 228/7

In [ ]:
# 228/6 # while calc mean, null/nan value is being ignored!

#but we dont want this

In [ ]:
df['age'].mean()

np.float64(39.666666666666664)

In [ ]:
# number of missing values in each col of the data
df.isnull().sum()

customer_id    0
name           1
age            1
city           1
amount         1
dtype: int64

In [ ]:
# percentage of missing values
100*df.isnull().mean()

customer_id     0.000000
name           14.285714
age            14.285714
city           14.285714
amount         14.285714
dtype: float64

In [ ]:
# Option 1 : Drop rows
# df = df.dropna()
# but with dropna there is a prblm it will drop all the rows where there'll a nan value.
# and it do a lot of missing data

In [ ]:
df.head()

   customer_id     name    age city    amount
0            1    Alice   25.0  BLR     500.0
1            2      Bob   30.0  DEL     200.0
2            2      Bob   30.0  DEL     200.0
3            3  Charlie    NaN  MUM     300.0
4            4    David  120.0  CHE  100000.0

In [ ]:
# Option 2 : filling the values
# numerical data
df['age']

0     25.0
1     30.0
2     30.0
3      NaN
4    120.0
5     28.0
6      5.0
Name: age, dtype: float64

In [ ]:
df["age"].fillna(df["amount"].median() , inplace = True)

In [ ]:
df["age"]

0     25.0
1     30.0
2     30.0
3    250.0
4    120.0
5     28.0
6      5.0
Name: age, dtype: float64

In [ ]:
df["age"].mean()

np.float64(69.71428571428571)

In [ ]:
df.columns

Index(['customer_id', 'name', 'age', 'city', 'amount'], dtype='object')

In [ ]:
df["amount"].fillna(df["amount"].median(), inplace = True)

/tmp/ipykernel_3262/2397346875.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["amount"].fillna(df["amount"].median(), inplace = True)

In [ ]:
df["amount"]

0       500.0
1       200.0
2       200.0
3       300.0
4    100000.0
5       250.0
6       150.0
Name: amount, dtype: float64

In [ ]:
df

   customer_id     name    age city    amount
0            1    Alice   25.0  BLR     500.0
1            2      Bob   30.0  DEL     200.0
2            2      Bob   30.0  DEL     200.0
3            3  Charlie  250.0  MUM     300.0
4            4    David  120.0  CHE  100000.0
5            5      NaN   28.0  BLR     250.0
6            6      Eve    5.0  NaN     150.0

In [ ]:
df.isnull().sum()

customer_id    0
name           1
age            0
city           1
amount         0
dtype: int64

In [ ]:
# Categorical :
# i. mode (most frequent value)
# ii. Create a new category (unknown)

In [ ]:
df['name'].mode()[0]

'Bob'

In [ ]:
df = pd.DataFrame({
    "customer_id": [1, 2, 2, 3, 4, 4, 5],
    "name": ["Alice", "Bob", "Bob", "Charlie", "David", "David", "Eve"],
    "city": ["BLR", "DEL", "DEL", "MUM", "CHE", "CHE", "BLR"],
    "amount": [500, 200, 200, 300, 150, 150, 400]
})

df

   customer_id     name city  amount
0            1    Alice  BLR     500
1            2      Bob  DEL     200
2            2      Bob  DEL     200
3            3  Charlie  MUM     300
4            4    David  CHE     150
5            4    David  CHE     150
6            5      Eve  BLR     400

In [ ]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
dtype: bool

In [ ]:
df.drop_duplicates(inplace = True, ignore_index= True)

In [ ]:
df

   customer_id     name city  amount
0            1    Alice  BLR     500
1            2      Bob  DEL     200
2            3  Charlie  MUM     300
3            4    David  CHE     150
4            5      Eve  BLR     400

In [ ]:
# subset of data! if we want to drop only particular cols
# df = df.drop_duplicates(subset=['customer_id'])

In [ ]:
df.head()

   customer_id     name city  amount
0            1    Alice  BLR     500
1            2      Bob  DEL     200
2            3  Charlie  MUM     300
3            4    David  CHE     150
4            5      Eve  BLR     400

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [1, 2, 2, 3, 4, 5, 6],
    "name": ["Alice", "Bob", "Bob", "Charlie", "David", np.nan, "Eve"],
    "age": [25, 30, 30, np.nan, 120, 28, 5],
    "city": ["BLR", "DEL", "DEL", "MUM", "CHE", "BLR", np.nan],
    "amount": [500, 200, 200, 300, 100000, np.nan, 150]
})

df

   customer_id     name    age city    amount
0            1    Alice   25.0  BLR     500.0
1            2      Bob   30.0  DEL     200.0
2            2      Bob   30.0  DEL     200.0
3            3  Charlie    NaN  MUM     300.0
4            4    David  120.0  CHE  100000.0
5            5      NaN   28.0  BLR       NaN
6            6      Eve    5.0  NaN     150.0

In [ ]:
df.isnull().sum()

customer_id    0
name           1
age            1
city           1
amount         1
dtype: int64

In [ ]:
#can i calculate mean and median of string no we cannot

In [ ]:
#when yu have a categorical data there are two option.
# 1. use most frequent value like in our dataset for name bob so in this cols for missing values we use it
# 2. create a new category (unknown)
# but adding ad creating sue our data means change our data so we have to use it very carefully.

In [ ]:
#let me show yu

# 1st way

df['name'].mode()[0]
# with .mode we use this to get most frequent or highest value used in your data in place of your na values.

'Bob'

In [ ]:
# 2nd way

df['name'].fillna("unknown", inplace = True)
df["city"].fillna(df["city"].mode()[0], inplace = True)

/tmp/ipykernel_3262/249046073.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['name'].fillna("unknown", inplace = True)
/tmp/ipykernel_3262/249046073.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].fillna(df["city"].mode()[0], inplace = True)

In [ ]:
df

   customer_id     name    age city    amount
0            1    Alice   25.0  BLR     500.0
1            2      Bob   30.0  DEL     200.0
2            2      Bob   30.0  DEL     200.0
3            3  Charlie    NaN  MUM     300.0
4            4    David  120.0  CHE  100000.0
5            5  unknown   28.0  BLR       NaN
6            6      Eve    5.0  BLR     150.0

QUESTIONS

In [ ]:
df = pd.DataFrame({
    "age": [25, 30, np.nan, 22, np.nan],
    "salary": [50000, np.nan, 60000, np.nan, 45000],
    "city": ["BLR", "DEL", np.nan, "MUM", "BLR"],
    "gender": ["M", np.nan, "F", "F", np.nan],
    "purchased": [1, 0, 1, 0, 1]
})

print(df)

    age   salary city gender  purchased
0  25.0  50000.0  BLR      M          1
1  30.0      NaN  DEL    NaN          0
2   NaN  60000.0  NaN      F          1
3  22.0      NaN  MUM      F          0
4   NaN  45000.0  BLR    NaN          1

In [ ]:
# Loop through each column and:
# If numeric → fill missing (np.nan) with mean
# If categorical → fill missing with "Unknown"

In [ ]:
# Loop through each column
for col in df.columns:

    print(col, "-", df[col].dtype)

    # If numeric column
    if df[col].dtype != "object":

        # Fill missing values with mean
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)

    else:
        # If categorical column
        # Fill missing values with "Unknown"
        df[col] = df[col].fillna("Unknown")

age - float64
salary - float64
city - object
gender - object
purchased - int64

QUESTION 2

In [ ]:
df = pd.DataFrame({
    "age": [25, np.nan, 40, 22, np.nan],
    "income": [50000, 60000, np.nan, 45000, np.nan],
    "city": ["BLR", np.nan, "MUM", "DEL", np.nan],
    "gender": ["M", "F", np.nan, "F", np.nan],
    "is_member": [1, 0, 1, 1, 0]   # binary column
})

print(df)

    age   income city gender  is_member
0  25.0  50000.0  BLR      M          1
1   NaN  60000.0  NaN      F          0
2  40.0      NaN  MUM    NaN          1
3  22.0  45000.0  DEL      F          1
4   NaN      NaN  NaN    NaN          0

In [ ]:
# Q. Conditional Filling with Special Rules

# Loop through each column and apply the following logic:
# If column is numeric:
  # If it is a binary column (only 0 and 1) → DO NOT change it
  # Otherwise → fill missing values with median
# If column is categorical (object):
  # Fill missing values with the most frequent value (mode)
# Return the cleaned DataFrame

In [ ]:
for col in df.columns:

    # Check if column is numeric
    if df[col].dtype != "object":

        # Get unique non-null values
        unique_vals = df[col].dropna().unique()

        # Check if binary column (only 0 and 1)
        if set(unique_vals).issubset({0, 1}):
            continue

        else:
            # Fill numeric missing values with median
            median_value = df[col].median()
            df[col] = df[col].fillna(median_value)

    else:
        # Fill categorical missing values with mode
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)

print(df)

    age   income city gender  is_member
0  25.0  50000.0  BLR      M          1
1  25.0  60000.0  BLR      F          0
2  40.0  50000.0  MUM      F          1
3  22.0  45000.0  DEL      F          1
4  25.0  50000.0  BLR      F          0

In [ ]:
# Outliers : extreme observation --> very different from rest of the data!!

In [ ]:
df = pd.DataFrame({
    "customer": ["A","B","C","D","E","F"],
    "amount": [100, 120, 130, 110, 115, 50000]  # 5000 is outlier
})

print(df)

  customer  amount
0        A     100
1        B     120
2        C     130
3        D     110
4        E     115
5        F   50000

In [ ]:
df["amount"].mean()

np.float64(8429.166666666666)

In [ ]:
df["amount"].median()

117.5

In [ ]:
#DETECT OUTLIERS.

# OPTION 1: BUSINESS RULE
#AMOUNT CANNOT BE GREATER THAN 1000

In [ ]:
# Option 2 : Using Stats! (Capping)
# Lower = Q1 - 1.5 * IQR
# Upper = Q3 + 1.5 * IQR
# IQR = Q3 - Q1 (75%ile - 25%ile)

#most used option

df['amount']

0      100
1      120
2      130
3      110
4      115
5    50000
Name: amount, dtype: int64

In [ ]:
df["amount"].median()

117.5

In [ ]:
Q1 = df['amount'].quantile(0.25)
Q3 = df['amount'].quantile(0.75)
IQR = Q3-Q1

In [ ]:
print(Q1)
print(Q3)
print(IQR)

111.25
127.5
16.25

In [ ]:
lower = Q1 - 1.5 * IQR #BOUND
upper = Q3 + 1.5 * IQR

In [ ]:
print(lower)
print(upper)

86.875
151.875

In [ ]:
# 2a. Filter
df_clean = df[(df["amount"] >= lower) & (df["amount"] <= upper)]

In [ ]:
# 2b. Capping
# Values < lower → set to lower
# Values > upper → set to upper
df['amount'] = np.clip(df['amount'],lower,upper)

In [ ]:
df

  customer   amount
0        A  100.000
1        B  120.000
2        C  130.000
3        D  110.000
4        E  115.000
5        F  151.875

In [ ]:
# Option 3 : Remove outliers