In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data1 = {
    'id': [1, 2],
    'name': ['Ajay', 'Drishan']
}
df1 = pd.DataFrame(data1)

In [ ]:
data2 = {
    'id': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df2 = pd.DataFrame(data2)

In [ ]:
df1

   id     name
0   1     Ajay
1   2  Drishan

In [ ]:
df2

   id       dept
0   1  Analytics
1   3       Tech

In [ ]:
pd.merge(df1, df2) #first table is left and 2nd one is right

   id  name       dept
0   1  Ajay  Analytics

In [ ]:
pd.merge(df1, df2, how = "inner", on = "id")

   id  name       dept
0   1  Ajay  Analytics

In [ ]:
pd.merge(df1, df2, how = "left" , on = "id")

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN

In [ ]:
pd.merge(df1, df2, how = "right" , on = "id")

   id  name       dept
0   1  Ajay  Analytics
1   3   NaN       Tech

In [ ]:
pd.merge(df1 , df2, how = "outer", on = "id")

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN
2   3      NaN       Tech

In [ ]:
data1 = {
    'id1': [1, 2],
    'name': ['Adi', 'palak']
}
df3 = pd.DataFrame(data1)
df3

   id1   name
0    1    Adi
1    2  palak

In [ ]:
data2 = {
    'id16': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df4 = pd.DataFrame(data2)
df4

   id16       dept
0     1  Analytics
1     3       Tech

In [ ]:
df3

   id1   name
0    1    Adi
1    2  palak

In [ ]:
df4

   id16       dept
0     1  Analytics
1     3       Tech

In [ ]:
# pd.merge(df1, df2, how = "inner" , on = "id")  it gives error beacuse id name is not same
# but how i make sure it runs for that we have to define on what table ehat perform

In [ ]:
pd.merge(df3, df4, how = "inner" , left_on = 'id1' , right_on = 'id16' )

   id1 name  id16       dept
0    1  Adi     1  Analytics

In [ ]:
#suffixes

# Customers DataFrame
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "order_id": ["A", "B", "C", "D"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai"]
})

# Orders DataFrame
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 2, 3, 5],
    "amount": [500, 300, 200, 700]
})

print(df_customers)
print('-'*32)
print(df_orders)

   customer_id order_id       city
0            1        A  Bangalore
1            2        B      Delhi
2            3        C     Mumbai
3            4        D    Chennai
--------------------------------
   order_id  customer_id  amount
0       101            1     500
1       102            2     300
2       103            3     200
3       104            5     700

In [ ]:
pd.merge(df_customers, df_orders, how = "inner" , on = "customer_id")

   customer_id order_id_x       city  order_id_y  amount
0            1          A  Bangalore         101     500
1            2          B      Delhi         102     300
2            3          C     Mumbai         103     200

In [ ]:
#see upper o/p it is showing x and y along with column anme but how do we find wht is x and wht is y it's diificult nd here we use suffixes inside suffixes we can define anything left right anyoe same or whtevr yu think easy for yu in remembering.



pd.merge(df_customers, df_orders, how = "inner", on = "customer_id",
    suffixes = ("_left" , "_right"))

#explicitly when yu define left or right then it is written along with column name either name_left , adi_right so yu will know from which column this table or column will come

   customer_id order_id_left       city  order_id_right  amount
0            1             A  Bangalore             101     500
1            2             B      Delhi             102     300
2            3             C     Mumbai             103     200

In [ ]:
 # T3: colors
t3 = pd.DataFrame({
    "colors": ["red", "blue"]
})

# T4: sizes
t4 = pd.DataFrame({
    "sizes": ["S", "M", "L", "XL"]
})

print(t3)
print('-'*32)
print(t4)

  colors
0    red
1   blue
--------------------------------
  sizes
0     S
1     M
2     L
3    XL

In [ ]:
#cross join
#it will do a cartesian product simply
pd.merge(t3,t4, how = "cross" )

  colors sizes
0    red     S
1    red     M
2    red     L
3    red    XL
4   blue     S
5   blue     M
6   blue     L
7   blue    XL

In [ ]:
df1=pd.DataFrame(
    {"letter":["a","b","c"],
     "num":range(3)})
df2=pd.DataFrame(
    {"value":[3,5,7]},
    index=["a","b","e"])

In [ ]:
df1

  letter  num
0      a    0
1      b    1
2      c    2

In [ ]:
df2

   value
a      3
b      5
e      7

In [ ]:
# col - index joining we can do in python

pd. merge(df1,df2, how = "inner", left_on = "letter", right_index = True)

  letter  num  value
0      a    0      3
1      b    1      5

In [ ]:
#we can do col to col join python
# we can do index to index join

#just wriste
#left_index = True, right_index= True

In [ ]:
df1 = pd.DataFrame({
    "name": ["A", "B", "C"],
    "score": [80, 85, 90]
})

df2 = pd.DataFrame({
    "name": ["D", "E"],
    "score": [70, 75]
})

print(df1)
print('-'*32)
print(df2)

  name  score
0    A     80
1    B     85
2    C     90
--------------------------------
  name  score
0    D     70
1    E     75

In [ ]:
#row wise concatenate on axis 0
# when we write ignore index so we do not get a same inddex again n gain 0 1 2 like we get 0 1 2 3 4 nd so on.

pd.concat([df1, df2], axis = 0, ignore_index= True)

  name  score
0    A     80
1    B     85
2    C     90
3    D     70
4    E     75

In [ ]:
pd.concat([df1, df2], axis = 1)
# yu can add - ignore_index true if want
# on axis 1 yu get cols

  name  score name  score
0    A     80    D   70.0
1    B     85    E   75.0
2    C     90  NaN    NaN

In [ ]:
import pandas as pd
import numpy as np

# Customers
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["A", "B", "C", "D", "E"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai", "Hyderabad"]
})

# Orders
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer_id": [1, 2, 2, 3, 6, 2],
    "amount": [500, 300, 200, 400, 800, 150]
})

# Payments
payments = pd.DataFrame({
    "payment_id": [201, 202, 203, 204],
    "order_id": [101, 102, 104, 107],
    "status": ["Paid", "Pending", "Paid", "Failed"]
})

Q/NA

In [ ]:
""" Q1. Inner Join Basics
Merge customers and orders to show only customers who have placed orders.
Output: customer_id, name, order_id, amount

Q2. Left Join (Unmatched Handling)
Show all customers and their orders (if any).
Identify customers who never placed an order

Q3. Right Join Insight
Show all orders with customer details.
Find orders that do not have a valid customer

Q4. Full Outer Join Analysis
Perform an outer join between customers and orders.
Count how many rows have missing values
Explain why they occur

Q5. Multi-table Join (Real-world scenario)
Combine customers, orders, and payments
Show: name, order_id, amount, payment status
Hint: You’ll need 2 merges

Q6. Cross Join Challenge 🔥
Create all possible combinations of:
customers × payment status
Questions:
Total number of rows?
Why is this useful?

Q7. Overlapping Columns + Cleanup
Create a new DataFrame:
customer_info = customers.rename(columns={"city": "location"})
Now:
Merge customers and customer_info
Handle duplicate columns properly
Clean final output (no _x, _y)
"""

ANSWERS..

In [ ]:
#Q1.
""" 1. Inner Join Basics
Merge customers and orders to show only customers who have placed orders.
Output: customer_id, name, order_id, amount
pd.merge(customers, orders, how = "inner" , on = "customer_id") """

pd.merge(customers, orders, how = "inner", on = "customer_id")

   customer_id name       city  order_id  amount
0            1    A  Bangalore       101     500
1            2    B      Delhi       102     300
2            2    B      Delhi       103     200
3            2    B      Delhi       106     150
4            3    C     Mumbai       104     400

In [ ]:
 # Q2. Left Join (Unmatched Handling)
 # Show all customers and their orders (if any).
 # Identify customers who never placed an order




pd.merge(customers, orders, how = "left", on = "customer_id")

   customer_id name       city  order_id  amount
0            1    A  Bangalore     101.0   500.0
1            2    B      Delhi     102.0   300.0
2            2    B      Delhi     103.0   200.0
3            2    B      Delhi     106.0   150.0
4            3    C     Mumbai     104.0   400.0
5            4    D    Chennai       NaN     NaN
6            5    E  Hyderabad       NaN     NaN

In [ ]:
 # Q3. Right Join Insight
 # Show all orders with customer details.
 # Find orders that do not have a valid customer

pd.merge(customers, orders, how = "right", on = "customer_id")

   customer_id name       city  order_id  amount
0            1    A  Bangalore       101     500
1            2    B      Delhi       102     300
2            2    B      Delhi       103     200
3            3    C     Mumbai       104     400
4            6  NaN        NaN       105     800
5            2    B      Delhi       106     150

In [ ]:
#Q4. Full Outer Join Analysis
 # Perform an outer join between customers and orders.
 # Count how many rows have missing values
 # Explain why they occur

pd.merge(customers, orders, how = "outer", on = "customer_id")

   customer_id name       city  order_id  amount
0            1    A  Bangalore     101.0   500.0
1            2    B      Delhi     102.0   300.0
2            2    B      Delhi     103.0   200.0
3            2    B      Delhi     106.0   150.0
4            3    C     Mumbai     104.0   400.0
5            4    D    Chennai       NaN     NaN
6            5    E  Hyderabad       NaN     NaN
7            6  NaN        NaN     105.0   800.0

In [ ]:
#Q5. Multi-table Join (Real-world scenario)
# Combine customers, orders, and payments
# Show: name, order_id, amount, payment status
# Hint: You’ll need 2 merges

# First merge: customers and orders
customers_orders = pd.merge(customers, orders, how = "left", on = "customer_id")

# Second merge: result with payments
final_df = pd.merge(customers_orders, payments, how = "left", on = "order_id")

# Select and display the required columns
print(final_df[['name', 'order_id', 'amount', 'status']])

  name  order_id  amount   status
0    A     101.0   500.0     Paid
1    B     102.0   300.0  Pending
2    B     103.0   200.0      NaN
3    B     106.0   150.0      NaN
4    C     104.0   400.0     Paid
5    D       NaN     NaN      NaN
6    E       NaN     NaN      NaN

In [ ]:
#Q6. Cross Join Challenge 🔥
# Create all possible combinations of:
# customers × payment status
# Questions:
# Total number of rows?
# Why is this useful?

# Extract unique payment statuses from the payments DataFrame
unique_payment_statuses = payments[['status']].drop_duplicates()

# Perform a cross join between customers and unique payment statuses
customer_payment_cross_join = pd.merge(customers, unique_payment_statuses, how='cross')

# Display the first few rows of the cross-joined DataFrame
display(customer_payment_cross_join.head())

# Calculate and display the total number of rows
total_rows = len(customer_payment_cross_join)
print(f"\nTotal number of rows: {total_rows}")

# Explain the usefulness of a cross join

   customer_id name       city   status
0            1    A  Bangalore     Paid
1            1    A  Bangalore  Pending
2            1    A  Bangalore   Failed
3            2    B      Delhi     Paid
4            2    B      Delhi  Pending

Total number of rows: 15

In [ ]:
#Q7. Overlapping Columns + Cleanup
# Create a new DataFrame: customer_info
customer_info = customers.rename(columns={"city": "location"})

# Merge customers and customer_info
# We'll merge on customer_id, and handle the duplicated 'name' column.
merged_customers_info = pd.merge(customers, customer_info, on="customer_id", how="inner", suffixes=('', '_info'))

# The prompt asks for 'no _x, _y' but since we have two 'name' columns,
# pandas will add suffixes by default. Let's explicitly drop the duplicate 'name' from customer_info
# as it's identical to the one in 'customers', and keep 'city' and 'location' as distinct.

# First, let's merge with default suffixes to see what we get.
# Then, we'll select the columns we want.
merged_df_with_suffixes = pd.merge(customers, customer_info, on="customer_id", how="inner")

# To clean the output and avoid _x, _y for identical columns like 'name',
# we can decide which one to keep. Since both 'name' columns are identical,
# we'll keep the one from the 'customers' DataFrame (implicitly 'name_x').
# The 'city' and 'location' columns are semantically different due to renaming, so both are desired.
final_q7_df = merged_df_with_suffixes[['customer_id', 'name_x', 'city', 'location']]
final_q7_df = final_q7_df.rename(columns={'name_x': 'name'}) # Rename 'name_x' back to 'name'

print("Merged and cleaned DataFrame for Q7:")
display(final_q7_df)

Merged and cleaned DataFrame for Q7:

   customer_id name       city   location
0            1    A  Bangalore  Bangalore
1            2    B      Delhi      Delhi
2            3    C     Mumbai     Mumbai
3            4    D    Chennai    Chennai
4            5    E  Hyderabad  Hyderabad