In [ ]:
# groupby , merges, pivot tables!

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["A", "B", "C", "D", "E"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Bangalore", "Delhi"],
    "amount": [500, 200, 300, 450, 150],
    "order_date": ["2024-01-10", "2024-02-15", "2024-03-20", "2024-01-25", "2024-02-05"]
})

df

   customer_id name       city  amount  order_date
0            1    A  Bangalore     500  2024-01-10
1            2    B      Delhi     200  2024-02-15
2            3    C     Mumbai     300  2024-03-20
3            4    D  Bangalore     450  2024-01-25
4            5    E      Delhi     150  2024-02-05

In [ ]:
# I want to create a new column -> category -> amount > 300 'high' otherwise 'low'
# use .apply function to do  this --> applies custom to rows / columns..

In [ ]:
def categ_amt (x):
 if x > 300 :
  return "high"
 else :
  return "low"

In [ ]:
df["category"] = df["amount"].apply(categ_amt)
df

   customer_id name       city  amount  order_date category
0            1    A  Bangalore     500  2024-01-10     high
1            2    B      Delhi     200  2024-02-15      low
2            3    C     Mumbai     300  2024-03-20      low
3            4    D  Bangalore     450  2024-01-25     high
4            5    E      Delhi     150  2024-02-05      low

In [ ]:
df

   customer_id name       city  amount  order_date category
0            1    A  Bangalore     500  2024-01-10     high
1            2    B      Delhi     200  2024-02-15      low
2            3    C     Mumbai     300  2024-03-20      low
3            4    D  Bangalore     450  2024-01-25     high
4            5    E      Delhi     150  2024-02-05      low

In [ ]:
# .apply ---> use for tarnsform a column , when yu want to apply a custom logic like high low right left..

In [ ]:
df.head()

   customer_id name       city  amount  order_date category
0            1    A  Bangalore     500  2024-01-10     high
1            2    B      Delhi     200  2024-02-15      low
2            3    C     Mumbai     300  2024-03-20      low
3            4    D  Bangalore     450  2024-01-25     high
4            5    E      Delhi     150  2024-02-05      low

In [ ]:
# let imagine i want banglore -- > BLR
# DELHI == >> DEL
#MUMABI == > MUM AND ALSO A NEW COLSS FOR ALL THESE

In [ ]:
# .map ---> 1 to 1 mapping

city_map = {
    "Bangalore": "BLR",
    "Delhi": "DEL",
    "Mumbai": "MUM"
}

In [ ]:
df["city_code"] = df["city"].map(
    city_map)

In [ ]:
df

   customer_id name       city  amount  order_date category city_code
0            1    A  Bangalore     500  2024-01-10     high       BLR
1            2    B      Delhi     200  2024-02-15      low       DEL
2            3    C     Mumbai     300  2024-03-20      low       MUM
3            4    D  Bangalore     450  2024-01-25     high       BLR
4            5    E      Delhi     150  2024-02-05      low       DEL

In [ ]:
#we can do i easire way  use replace

df["city_code2"] = df["city"].replace({
    "Bangalore": "BLR",
    "Delhi": "DEL",
    "Mumbai": "MUM"
})
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL

In [ ]:
#THERE IS KEY A DIFF B/W MAP AND REPLACE
# MAP() -- RETUNS NAN IF something missing like we don't pass a value for mumbai
# REPLACE() --- leaves unchanged if not found it returns same value as it is.

In [ ]:
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL

In [ ]:
#if we wannt to know cols and their data types we use
df.dtypes

customer_id     int64
name           object
city           object
amount          int64
order_date     object
category       object
city_code      object
city_code2     object
dtype: object

In [ ]:
#in python we convert data types for that
df["order_date"] = pd.to_datetime(df["order_date"])

In [ ]:
df.dtypes

customer_id             int64
name                   object
city                   object
amount                  int64
order_date     datetime64[ns]
category               object
city_code              object
city_code2             object
dtype: object

In [ ]:
#why we convert this reason....
#for arithmetic and we can fetch alot of information from this

#for ex

df["year"]= df["order_date"].dt.year
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024

In [ ]:
df["day"]= df["order_date"].dt.day
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5

In [ ]:
# but sometimes we might wondering who understand this month like series 1 2 3
# instead 1 2 if jan feb will that's good for reading understanding and showing also
# so we can do this

df["day_name"]= df["order_date"].dt.day_name()

df["month_name"]= df["order_date"].dt.month_name()
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February

In [ ]:
df["quarter"] = df["order_date"].dt.quarter
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1

In [ ]:
#we can also find all these.

# df["is_month_start"] = df["order_date"].dt.is_month_start  # First day of month
# df["is_month_end"] = df["order_date"].dt.is_month_end      # Last day of month
# df["is_year_start"] = df["order_date"].dt.is_year_start    # Jan 1
# df["is_year_end"] = df["order_date"].dt.is_year_end        # Dec 31
# df["day_of_week"] = df["order_date"].dt.dayofweek   # Monday=0, Sunday=6
# df["weekday"] = df["order_date"].dt.weekday         # Same as above
# df["week_of_year"] = df["order_date"].dt.isocalendar().week  # ISO week number
# df["day_of_year"] = df["order_date"].dt.dayofyear   # Day number in year (1–365)

In [ ]:
# Days since '2024-04-01'
# you want to create new cols and want to find out of no of days from this date

In [ ]:
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1

In [ ]:
df["days_since"]= (pd.Timestamp('2024-04-01') - df["order_date"]).dt.days
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter,days_since
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1,82
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1,46
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1,12
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1,67
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1,56

In [ ]:
pd.to_datetime(df["order_date"]).dt.tz_localize("Asia/Kolkata").dt.tz_convert("UTC")

0   2024-01-09 18:30:00+00:00
1   2024-02-14 18:30:00+00:00
2   2024-03-19 18:30:00+00:00
3   2024-01-24 18:30:00+00:00
4   2024-02-04 18:30:00+00:00
Name: order_date, dtype: datetime64[ns, UTC]

In [ ]:
sales = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["A", "B", "C", "D", "E"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Bangalore", "Delhi"],
    "amount": [500, 200, 300, 450, 150],
    "order_date": ["2024-01-10", "2024-02-15", "2024-03-20", "2024-01-25", "2024-02-05"]
})

df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter,days_since
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1,82
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1,46
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1,12
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1,67
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1,56

In [ ]:
sales = pd.DataFrame({
    "customer_id": [1,1,2,2,3,3],
    "month": ["Jan","Feb","Jan","Feb","Jan","Feb"],
    "sales": [100,150,200,250,300,350]
})
sales

   customer_id month  sales
0            1   Jan    100
1            1   Feb    150
2            2   Jan    200
3            2   Feb    250
4            3   Jan    300
5            3   Feb    350

In [ ]:
# Long -> Wide Conversion
pivot_df = sales.pivot(
    index = 'customer_id',
    columns = 'month',
    values = 'sales'
)
pivot_df

month        Feb  Jan
customer_id
1            150  100
2            250  200
3            350  300

In [ ]:
# Wide to Long conversion
melt_df = pd.melt(
    pivot_df.reset_index(),
    id_vars = 'customer_id',
    var_name = 'month',
    value_name = 'sales'

)

melt_df

   customer_id month  sales
0            1   Feb    150
1            2   Feb    250
2            3   Feb    350
3            1   Jan    100
4            2   Jan    200
5            3   Jan    300

In [ ]:
# id_vars	Keep these columns fixed
# var_name	Name for melted column names
# value_name	Name for melted values

In [ ]:
df.head()

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter,days_since
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1,82
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1,46
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1,12
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1,67
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1,56

In [ ]:
df['new_amt'] = df['amount']*100
df

,customer_id,name,city,amount,order_date,category,city_code,city_code2,year,day,day_name,month_name,quarter,days_since,new_amt
0,1,A,Bangalore,500,2024-01-10,high,BLR,BLR,2024,10,Wednesday,January,1,82,50000
1,2,B,Delhi,200,2024-02-15,low,DEL,DEL,2024,15,Thursday,February,1,46,20000
2,3,C,Mumbai,300,2024-03-20,low,MUM,MUM,2024,20,Wednesday,March,1,12,30000
3,4,D,Bangalore,450,2024-01-25,high,BLR,BLR,2024,25,Thursday,January,1,67,45000
4,5,E,Delhi,150,2024-02-05,low,DEL,DEL,2024,5,Monday,February,1,56,15000

QUESTIONS

In [ ]:
df = pd.DataFrame({
    "order_id": [101,102,103,104,105,106,107],
    "customer": ["A","B","C","A","B","C","D"],
    "city": ["Bangalore","Delhi","Mumbai","Bangalore","Delhi","Mumbai","Chennai"],
    "amount": [500,200,300,450,150,350,400],
    "category": ["Electronics","Clothing","Electronics","Clothing","Electronics","Clothing","Electronics"],
    "order_date": [
        "2024-01-10",
        "2024-02-15",
        "2024-03-20",
        "2024-01-25",
        "2024-02-05",
        "2024-03-15",
        "2024-01-05"
    ]
})

df

   order_id customer       city  amount     category  order_date
0       101        A  Bangalore     500  Electronics  2024-01-10
1       102        B      Delhi     200     Clothing  2024-02-15
2       103        C     Mumbai     300  Electronics  2024-03-20
3       104        A  Bangalore     450     Clothing  2024-01-25
4       105        B      Delhi     150  Electronics  2024-02-05
5       106        C     Mumbai     350     Clothing  2024-03-15
6       107        D    Chennai     400  Electronics  2024-01-05

In [ ]:
# Q1. 📅 Date Transformation and Feature Extraction

# The order_date column is currently stored as a string.

# Your task is to:

# Convert the order_date column into a proper datetime format.
# From this datetime column, create the following new columns:
# year → year of the order
# month → numeric month (1–12)
# day → day of the month
# month_name → full month name (e.g., January)
# is_weekend → True if the order was placed on Saturday or Sunday, else False

#convert to date time format (very imp before using .dt)
df["order_date"] = pd.to_datetime(df["order_date"])

#Extract component.
df["year"] = df["order_date"].dt.year
df["month"]= df["order_date"].dt.month
df["day"] = df["order_date"].dt.day

#Extract readable month name jan feb
df["month_name"]= df["order_date"].dt.month_name()

#check if weeekend
df["is_weekend"] = df["order_date"].dt.dayofweek >= 5
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend
0,101,A,Bangalore,500,Electronics,2024-01-10,2024,1,10,January,False
1,102,B,Delhi,200,Clothing,2024-02-15,2024,2,15,February,False
2,103,C,Mumbai,300,Electronics,2024-03-20,2024,3,20,March,False
3,104,A,Bangalore,450,Clothing,2024-01-25,2024,1,25,January,False
4,105,B,Delhi,150,Electronics,2024-02-05,2024,2,5,February,False
5,106,C,Mumbai,350,Clothing,2024-03-15,2024,3,15,March,False
6,107,D,Chennai,400,Electronics,2024-01-05,2024,1,5,January,False

In [ ]:
# Q2. 🔧 Applying Business Logic Using apply()

# Create a new column called spend_type based on the amount spent by each customer.

# Rules:

# If amount is greater than or equal to 400, label as "High"
# If amount is between 200 and 399, label as "Medium"
# If amount is less than 200, label as "Low"

# Use the apply() function with a lambda expression.

#define a function for bussiness logic.
def categorize_spend(x):
  if x >= 400:
    return "high"
  elif x >= 200:
      return "medium"
  else:
    return "low"

    #apply the function to the column.
  df["spend_type"] = df["amount"].apply(categorize_spend)
  df

In [ ]:
# Q3. 🔄 Value Transformation using map() and replace()

# You need to standardize and encode categorical values.

# Steps:

# Create a new column city_code by mapping:
# Bangalore → BLR
# Delhi → DEL
# Mumbai → MUM
# Chennai → CHE
# Modify the existing category column by replacing:
# Electronics → E
# Clothing → C

#map city name s--> codes 1 to 1 mapping
city_map = {
     "Bangalore": "BLR",
     "Delhi": "DEL",
     "Mumbai": "MUM",
     "Chennai": "CHE"

}
df["city_code"] = df ["city"].map(city_map)

#replace values inside cols (cleaning/encoding)
df["category"] = df ["category"].replace({
    "Electronics" : "E",

    'Clothing': "C"

    })
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code
0,101,A,Bangalore,500,E,2024-01-10,2024,1,10,January,False,BLR
1,102,B,Delhi,200,C,2024-02-15,2024,2,15,February,False,DEL
2,103,C,Mumbai,300,E,2024-03-20,2024,3,20,March,False,MUM
3,104,A,Bangalore,450,C,2024-01-25,2024,1,25,January,False,BLR
4,105,B,Delhi,150,E,2024-02-05,2024,2,5,February,False,DEL
5,106,C,Mumbai,350,C,2024-03-15,2024,3,15,March,False,MUM
6,107,D,Chennai,400,E,2024-01-05,2024,1,5,January,False,CHE

In [ ]:
# Q4. Reshaping Data using Pivot

# You are asked to analyze total spending by each customer across categories.

# Create a pivot table such that:

# Rows represent customer
# Columns represent category
# Values represent the total amount spent

pivot_df = df.pivot_table(
         index= "customer",  #rows
         columns = "category", #cols
         values="amount",  #values to aggregation
         aggfunc="sum"    #agg function
)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code
0,101,A,Bangalore,500,E,2024-01-10,2024,1,10,January,False,BLR
1,102,B,Delhi,200,C,2024-02-15,2024,2,15,February,False,DEL
2,103,C,Mumbai,300,E,2024-03-20,2024,3,20,March,False,MUM
3,104,A,Bangalore,450,C,2024-01-25,2024,1,25,January,False,BLR
4,105,B,Delhi,150,E,2024-02-05,2024,2,5,February,False,DEL
5,106,C,Mumbai,350,C,2024-03-15,2024,3,15,March,False,MUM
6,107,D,Chennai,400,E,2024-01-05,2024,1,5,January,False,CHE

In [ ]:
# Q5. Converting Wide Data Back to Long Format (Melt)

# Using the pivot table created in Q4:

# Convert the wide-format pivot table back into a long-format dataset
# The final output should contain:
# customer
# category
# amount

pivot_df = df.pivot_table(
    index="customer",        # rows
    columns="category",      # columns
    values="amount",         # values to aggregate
    aggfunc="sum"            # aggregation function
)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code
0,101,A,Bangalore,500,E,2024-01-10,2024,1,10,January,False,BLR
1,102,B,Delhi,200,C,2024-02-15,2024,2,15,February,False,DEL
2,103,C,Mumbai,300,E,2024-03-20,2024,3,20,March,False,MUM
3,104,A,Bangalore,450,C,2024-01-25,2024,1,25,January,False,BLR
4,105,B,Delhi,150,E,2024-02-05,2024,2,5,February,False,DEL
5,106,C,Mumbai,350,C,2024-03-15,2024,3,15,March,False,MUM
6,107,D,Chennai,400,E,2024-01-05,2024,1,5,January,False,CHE

In [ ]:
# Q6. Efficient Computation using Vectorization

# Create a new column called discounted_amount.

# Rules:

# If amount is greater than 300, apply a 10% discount
# Otherwise, keep the amount unchanged

# Important:
# Do NOT use apply() — use vectorized operations.

 #First apply 10% discount to all
df["discounted_amount"] = df["amount"] * 0.9

# Then overwrite where condition is not met
df.loc[df["amount"] <= 300, "discounted_amount"] = df["amount"]
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount
0,101,A,Bangalore,500,E,2024-01-10,2024,1,10,January,False,BLR,450.0
1,102,B,Delhi,200,C,2024-02-15,2024,2,15,February,False,DEL,200.0
2,103,C,Mumbai,300,E,2024-03-20,2024,3,20,March,False,MUM,300.0
3,104,A,Bangalore,450,C,2024-01-25,2024,1,25,January,False,BLR,405.0
4,105,B,Delhi,150,E,2024-02-05,2024,2,5,February,False,DEL,150.0
5,106,C,Mumbai,350,C,2024-03-15,2024,3,15,March,False,MUM,315.0
6,107,D,Chennai,400,E,2024-01-05,2024,1,5,January,False,CHE,360.0

In [ ]:
# Q7. End-to-End Data Transformation Pipeline

# Perform the following sequence of operations:

# Convert order_date to datetime (if not already done)
# Extract the month name into a new column
# Create a pivot table where:
# Rows = month
# Columns = category
# Values = total amount
# Convert this pivot table back into long format using melt()

# Final output should look like:

# month | category | total_amount

# Extract month name
df["month"] = df["order_date"].dt.month_name()

# Pivot: month vs category → total amount
temp = df.pivot_table(
    index="month",
    columns="category",
    values="amount",
    aggfunc="sum"
)

# Melt back to long format
q7 = pd.melt(
    temp.reset_index(),
    id_vars=["month"],
    var_name="category",
    value_name="total_amount"
)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0

In [ ]:
# Q8. A business analyst wants to understand revenue trends across cities and months.

# Your task:

# Extract the month from order_date
# Calculate total revenue for each city per month
# Sort the result in descending order of revenue

# Final output should help identify:

# Which city generates the highest revenue
# In which month

# Group by city and month → total revenue
q8 = df.groupby(["city", "month"])["amount"].sum().reset_index()

# Sort highest revenue first
q8 = q8.sort_values(by="amount", ascending=False)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0

In [ ]:
# Q9. Pivot with Multiple Aggregations (Advanced Pivot)

# You previously created a pivot table for total spend. Now, the business wants more insights per customer.

# Create a pivot table where:

# Rows represent customer
# Columns represent category
# Values represent amount

# But this time:

# Calculate both:
# Total amount spent (sum)
# Average amount spent (mean)

# Your output should show multiple aggregated values for each category.


q9 = df.pivot_table(
    index="customer",
    columns="category",
    values="amount",
    aggfunc=["sum", "mean"]  # multiple aggregations
)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0

In [ ]:
# Q10. Filtering + Transformation (Real-world logic)

# A marketing team only wants to analyze high-value transactions.

# Steps:

# Filter the dataset to include only rows where amount ≥ 300
# From this filtered data:
# Create a new column high_value_flag = "Yes"
# Return only:
# customer, city, amount, high_value_flag


# Filter rows
q10 = df[df["amount"] >= 300].copy()

# Add flag column
q10["high_value_flag"] = "Yes"

# Select required columns
q10 = q10[["customer", "city", "amount", "high_value_flag"]]

df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0

In [ ]:
# Q11. Conditional Transformation without apply()

# Create a new column order_size based on amount:

# Rules:

# amount ≥ 400 → "Large"
# 200 ≤ amount < 400 → "Medium"
# < 200 → "Small"

# Constraint:

# Do NOT use apply()
# Use vectorized logic (np.select or boolean masking)

conditions = [
    df["amount"] >= 400,
    (df["amount"] >= 200) & (df["amount"] < 400),
    df["amount"] < 200
]

choices = ["Large", "Medium", "Small"]

# Apply vectorized conditional logic, providing a string default value
df["order_size"] = np.select(conditions, choices, default=None)
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount,order_size
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0,Large
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0,Medium
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0,Medium
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0,Large
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0,Small
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0,Medium
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0,Large

In [ ]:
# Q12. Time-based Aggregation (Important Real Use Case)

# The business wants to track monthly revenue trends.

# Steps:

# Extract month_name from order_date
# Group the data by month_name
# Calculate total amount per month
# Sort months in calendar order (NOT alphabetical)

# Final output should clearly show:

# month_name | total_revenue


# Group by month
q12 = df.groupby("month_name")["amount"].sum().reset_index()

# Define correct calendar order (important!)
month_order = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]

# Convert to ordered categorical for sorting
q12["month_name"] = pd.Categorical(q12["month_name"], categories=month_order, ordered=True)

# Sort properly (not alphabetical)
q12 = q12.sort_values("month_name")
df

,order_id,customer,city,amount,category,order_date,year,month,day,month_name,is_weekend,city_code,discounted_amount,order_size
0,101,A,Bangalore,500,E,2024-01-10,2024,January,10,January,False,BLR,450.0,Large
1,102,B,Delhi,200,C,2024-02-15,2024,February,15,February,False,DEL,200.0,Medium
2,103,C,Mumbai,300,E,2024-03-20,2024,March,20,March,False,MUM,300.0,Medium
3,104,A,Bangalore,450,C,2024-01-25,2024,January,25,January,False,BLR,405.0,Large
4,105,B,Delhi,150,E,2024-02-05,2024,February,5,February,False,DEL,150.0,Small
5,106,C,Mumbai,350,C,2024-03-15,2024,March,15,March,False,MUM,315.0,Medium
6,107,D,Chennai,400,E,2024-01-05,2024,January,5,January,False,CHE,360.0,Large