In [ ]:
# pandas :
# series : indexing slicing masking filtering
# dataframes : head tail shape describe info filterations selecting 1 / multiple cols
# read csv value, sort_values (asc/desc) inplace = true transpose
# manipulating data : adding a new col!

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],

        "score":[90,80,85,75,95,60,65],

       "sport":["Wrestling","Football","Skiing","Swimming",
                "Tennis","Karete","Surfing"],

        "sex":["M","M","M","M","F","F","F"]}

In [ ]:
df= pd.DataFrame(data=data,
                 index=["one","two","three","four","five",
                       "six","seven"])

In [ ]:
df

          name  score      sport sex
one       Bill     90  Wrestling   M
two        Tom     80   Football   M
three      Tim     85     Skiing   M
four      John     75   Swimming   M
five      Alex     95     Tennis   F
six    Vanessa     60     Karete   F
seven     Kate     65    Surfing   F

In [ ]:
df.reset_index()
# 1. old index -> became a new column
# 2. new index now

   index     name  score      sport sex
0    one     Bill     90  Wrestling   M
1    two      Tom     80   Football   M
2  three      Tim     85     Skiing   M
3   four     John     75   Swimming   M
4   five     Alex     95     Tennis   F
5    six  Vanessa     60     Karete   F
6  seven     Kate     65    Surfing   F

In [ ]:
df.reset_index(drop=True)
# 1. old index has been removed
# 2. new index is created

      name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [ ]:
df.head()
# 1. original data with index : one, two, .... --> CORRECT!!
# 2. df with 1) old index as col and 2) new index 0,1,2,.....
# 3. df with only the new index

       name  score      sport sex
one    Bill     90  Wrestling   M
two     Tom     80   Football   M
three   Tim     85     Skiing   M
four   John     75   Swimming   M
five   Alex     95     Tennis   F

In [ ]:
# 1.
# df = df.reset_index(drop=True)

# 2.
df.reset_index(drop=True, inplace=True)

df

      name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [ ]:
df.set_index('name',inplace=True)
df

         score      sport sex
name
Bill        90  Wrestling   M
Tom         80   Football   M
Tim         85     Skiing   M
John        75   Swimming   M
Alex        95     Tennis   F
Vanessa     60     Karete   F
Kate        65    Surfing   F

In [ ]:
df.reset_index(drop=True,inplace=True)
df

   score      sport sex
0     90  Wrestling   M
1     80   Football   M
2     85     Skiing   M
3     75   Swimming   M
4     95     Tennis   F
5     60     Karete   F
6     65    Surfing   F

In [ ]:
df.sort_values(by='score', inplace=True)
df

   score      sport sex
5     60     Karete   F
6     65    Surfing   F
3     75   Swimming   M
1     80   Football   M
2     85     Skiing   M
0     90  Wrestling   M
4     95     Tennis   F

In [ ]:
df.sort_values(by='score', inplace=True, ignore_index=True)
df

   score      sport sex
0     60     Karete   F
1     65    Surfing   F
2     75   Swimming   M
3     80   Football   M
4     85     Skiing   M
5     90  Wrestling   M
6     95     Tennis   F

In [ ]:
data = pd.DataFrame(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
        [12, 13, 14, 15]
    ],
    index=["London", "Paris", "Berlin", "Istanbul"],
    columns=["one", "two", "three", "four"]
)
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
data.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [ ]:
# data[0] # error

data[0:1] #1st row

        one  two  three  four
London    0    1      2     3

In [ ]:
# 2 ways : iloc v/s loc

# iloc : integer based indexing!

data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
print(data.iloc[0,0]) # 1st row, 1st col

0

In [ ]:
print(data.iloc[2,3]) # 2nd index row, 3 col index -> 3rd row and 4th col

11

In [ ]:
# loc : label based indexing

data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
print(data.loc["Paris","four"])

7

In [ ]:
data = pd.DataFrame(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
        [12, 13, 14, 15]
    ],
    index=["London", "Paris", "Berlin", "Istanbul"],
    columns=["one", "two", "three", "four"]
)

data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
data.head()

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
# Q1
# Select the row for Paris.
data.loc["Paris"]

one      4
two      5
three    6
four     7
Name: Paris, dtype: int64

In [ ]:
# Q2
# Select the column "two".
data['two']

London       1
Paris        5
Berlin       9
Istanbul    13
Name: two, dtype: int64

In [ ]:
# Q3
# Select rows London and Berlin, and columns "one" and "three".
data.loc[["London","Berlin"],["one","three"]]

        one  three
London    0      2
Berlin    8     10

In [ ]:
# Q4
# Using .iloc, select:
# first 3 rows
# last 2 columns
data.iloc[:3,2:]

        three  four
London      2     3
Paris       6     7
Berlin     10    11

In [ ]:
# Q5
# Using .loc, select:
# rows from Paris to Istanbul
# columns from "two" to "four"
data.loc["Paris":"Istanbul", "two":"four"]

          two  three  four
Paris       5      6     7
Berlin      9     10    11
Istanbul   13     14    15

In [ ]:
df = pd.DataFrame({
    "Name": ["Amit", "Sara", "John", "Neha", "Raj", "Priya", "Arjun", "Meera", "David", "Kiran"],
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai", "Bangalore", "Delhi", "Pune", "Mumbai", "Bangalore"],
    "Country": ["India", "India", "India", "India", "India", "India", "India", "India", "India", "India"],
    "Salary": [50000, 60000, 45000, 80000, 55000, 70000, 52000, 48000, 62000, 75000]
})

df

    Name   ID       City Country  Salary
0   Amit  101      Delhi   India   50000
1   Sara  102     Mumbai   India   60000
2   John  103       Pune   India   45000
3   Neha  104      Delhi   India   80000
4    Raj  105     Mumbai   India   55000
5  Priya  106  Bangalore   India   70000
6  Arjun  107      Delhi   India   52000
7  Meera  108       Pune   India   48000
8  David  109     Mumbai   India   62000
9  Kiran  110  Bangalore   India   75000

In [ ]:
# Q1 (AND condition)
# Get employees who are from Delhi AND have Salary > 50000
df[(df['City'] == 'Delhi') & (df['Salary']>50000)]

    Name   ID   City Country  Salary
3   Neha  104  Delhi   India   80000
6  Arjun  107  Delhi   India   52000

In [ ]:
# Q2 (OR condition)
# Get employees who are from Mumbai OR have Salary > 70000
df[(df['City'] == 'Mumbai') | (df['Salary']>70000)]
# | : pipe operation

    Name   ID       City Country  Salary
1   Sara  102     Mumbai   India   60000
3   Neha  104      Delhi   India   80000
4    Raj  105     Mumbai   India   55000
8  David  109     Mumbai   India   62000
9  Kiran  110  Bangalore   India   75000

In [ ]:
# Q3 (Greater than + Equal condition on different columns)
# Get employees where Salary >= 60000 AND City = Bangalore
df[(df.Salary >= 60000) & (df.City == "Bangalore")]

    Name   ID       City Country  Salary
5  Priya  106  Bangalore   India   70000
9  Kiran  110  Bangalore   India   75000

In [ ]:
# Q4 (NOT condition)
# Get employees who are NOT from Pune
df[df['City']!='Pune']

    Name   ID       City Country  Salary
0   Amit  101      Delhi   India   50000
1   Sara  102     Mumbai   India   60000
3   Neha  104      Delhi   India   80000
4    Raj  105     Mumbai   India   55000
5  Priya  106  Bangalore   India   70000
6  Arjun  107      Delhi   India   52000
8  David  109     Mumbai   India   62000
9  Kiran  110  Bangalore   India   75000

In [ ]:
# Q5 (Mixed condition – AND + OR)
# Get employees who:
# are from Delhi AND Salary > 50000
# OR
# are from Mumbai AND Salary >= 60000
# df[(() & ()) |
#    (() & ())]
df[
    ((df["City"] == "Delhi") & (df["Salary"] > 50000)) |
    ((df["City"] == "Mumbai") & (df["Salary"] >= 60000))
]

    Name   ID    City Country  Salary
1   Sara  102  Mumbai   India   60000
3   Neha  104   Delhi   India   80000
6  Arjun  107   Delhi   India   52000
8  David  109  Mumbai   India   62000