In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "name": ["  alice  ", "BOB", "charlie ", "David", "eve"],
    "email": ["alice@gmail.com", "bob@yahoo.com", "charlie@outlook.com", "david@gmail.com", "eve@yahoo.com"],
    "phone": ["+91-9876543210", "98765 43210", "(+91)9876543210", "9876543210", "98-7654-3210"],
    "city": ["bangalore", "DELHI", "Mumbai ", "chennai", "Bangalore"],
    "category": ["Electronics", "electronics", "Clothing", "clothing", "ELECTRONICS"]
})

df

        name                email            phone       city     category
0    alice        alice@gmail.com   +91-9876543210  bangalore  Electronics
1        BOB        bob@yahoo.com      98765 43210      DELHI  electronics
2   charlie   charlie@outlook.com  (+91)9876543210    Mumbai      Clothing
3      David      david@gmail.com       9876543210    chennai     clothing
4        eve        eve@yahoo.com     98-7654-3210  Bangalore  ELECTRONICS

In [ ]:
#"alice"
#" alice "
# will this work if we join it no it doesn't work

In [ ]:
# for this we allows vectorized operation on entire column we want to fix spaces trailing

In [ ]:
df["name"] = df["name"].str.strip()
#.strip is used to remove loading and trailing spaces in the data

In [ ]:
df["city"] = df["city"].str.strip()

In [ ]:
df

      name                email            phone       city     category
0    alice      alice@gmail.com   +91-9876543210  bangalore  Electronics
1      BOB        bob@yahoo.com      98765 43210      DELHI  electronics
2  charlie  charlie@outlook.com  (+91)9876543210     Mumbai     Clothing
3    David      david@gmail.com       9876543210    chennai     clothing
4      eve        eve@yahoo.com     98-7654-3210  Bangalore  ELECTRONICS

In [ ]:
df["city"] = df["city"].str.replace("bangalore","blr")
df

#but why this only work on bangalore written in small because other one written in capital and qe know python is case sensitive.

      name                email            phone       city     category
0    alice      alice@gmail.com   +91-9876543210        blr  Electronics
1      BOB        bob@yahoo.com      98765 43210      DELHI  electronics
2  charlie  charlie@outlook.com  (+91)9876543210     Mumbai     Clothing
3    David      david@gmail.com       9876543210    chennai     clothing
4      eve        eve@yahoo.com     98-7654-3210  Bangalore  ELECTRONICS

In [ ]:
#can we do this for entire city column yes we can for that
df["city"] = df["city"].str.lower()
df

      name                email            phone       city     category
0    alice      alice@gmail.com   +91-9876543210        blr  Electronics
1      BOB        bob@yahoo.com      98765 43210      delhi  electronics
2  charlie  charlie@outlook.com  (+91)9876543210     mumbai     Clothing
3    David      david@gmail.com       9876543210    chennai     clothing
4      eve        eve@yahoo.com     98-7654-3210  bangalore  ELECTRONICS

In [ ]:
df["category"] = df["category"].str.lower()
df
#we do this for entire data cols

      name                email            phone       city     category
0    alice      alice@gmail.com   +91-9876543210        blr  electronics
1      BOB        bob@yahoo.com      98765 43210      delhi  electronics
2  charlie  charlie@outlook.com  (+91)9876543210     mumbai     clothing
3    David      david@gmail.com       9876543210    chennai     clothing
4      eve        eve@yahoo.com     98-7654-3210  bangalore  electronics

In [ ]:
df["category"] = df["category"].str.upper()
df

      name                email            phone       city     category
0    alice      alice@gmail.com   +91-9876543210        blr  ELECTRONICS
1      BOB        bob@yahoo.com      98765 43210      delhi  ELECTRONICS
2  charlie  charlie@outlook.com  (+91)9876543210     mumbai     CLOTHING
3    David      david@gmail.com       9876543210    chennai     CLOTHING
4      eve        eve@yahoo.com     98-7654-3210  bangalore  ELECTRONICS

In [ ]:
x = "hi"

In [ ]:
x.lower()

'hi'

In [ ]:
x.upper()

'HI'

In [ ]:
x.title()

'Hi'

In [ ]:
## Regular Expression (re) : way to define pattern in the text.
# re module in python helps us finding, matching, manipulaitng text!

In [ ]:
# Phone number :
# +91 9999 123456
# +91-9999-123-456 @this is correct way
# +919999123456
# +919999-123-456

# the only correct format is +91-4digits-3digits-3digits

In [ ]:
#now how yu write this command and run it
import re

In [ ]:
# 1. re.search()   -> search for the first match of pattern in a string
# 2. re.findall()  -> returns all non overlapping matches as a list
# 3. re.match()    -> match the pattern only at the start of the string
# 4. re.sub()      -> replaces part of the string
# 5. re.compile()  -> reusable object

In [ ]:
# Example 1 : Find all word-like sequences (alphanumeric + underscore)
text = "Hello_World123, how are you?"

In [ ]:
re.findall(r"\w", text)
# \w  : word chars (letter, digits, underscore)
# and removes question marks and spaces

['H',
 'e',
 'l',
 'l',
 'o',
 '_',
 'W',
 'o',
 'r',
 'l',
 'd',
 '1',
 '2',
 '3',
 'h',
 'o',
 'w',
 'a',
 'r',
 'e',
 'y',
 'o',
 'u']

In [ ]:
re.findall(r"\w+",text)
#w+: means one or repitions of \w

['Hello_World123', 'how', 'are', 'you']

In [ ]:
text = 'Masai School is 10 year old!'
# I want to find position of only digits in the text?

In [ ]:
re.search(r"\d",text)

# \d tells us on which place from counting left our digits lies we can simply find it by reading but wehn we works on
# a large data set it is dificult to find and here \d comes into picture.

In [ ]:
re.search(r"\d+",text)

In [ ]:
re.findall(r'\d+',text)
#now we don't want a position we want entire digit and for that we use (\d+)

['100', '200', '5000', '10000', '100000']

In [ ]:
text = "Masai is 100,200,5000,10000,100000 years old!"
# find all digits in this string!

In [ ]:
re.findall(r"\d+",text)

['100', '200', '5000', '10000', '100000']

In [ ]:
re.findall(r"\d",text)

['1',
 '0',
 '0',
 '2',
 '0',
 '0',
 '5',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0']

In [ ]:
text = "A1 B2 C2"
# fetch numbers from this?

In [ ]:
re.findall(r"\d",text)

['1', '2', '2']

In [ ]:
text = "A1 B2 C2"
# find all non digits!

In [ ]:
re.findall(r"\D",text)
# \D  → splits into single non-digit characters.

['A', ' ', 'B', ' ', 'C']

In [ ]:
re.findall(r'\D+',text)
# \D+ → collects continuous runs of non-digits into a string.

['A', ' B', ' C']

In [ ]:
text = 'Hi Masai'
# does this str end with Masai or not?

In [ ]:
re.findall("Masai$",text)  # $ : means ends with

['Masai']

In [ ]:
re.findall('School$',text) # $ : ends with

[]

In [ ]:
re.findall('^Hi',text)
# caret operator ^ this is it returns entire data

['Hi']

In [ ]:
re.findall('^Hello',text)
# caret! and no data presnt it returns null like this

[]

In [ ]:
# abc@gmail.com
# abc@yahoo.com
# abc@hotmail.com
# ...

In [ ]:
text = "PIN : 7890"

In [ ]:
re.findall(r"\d",text)

['7', '8', '9', '0']

In [ ]:
re.findall(r"\d+",text)

['7890']

In [ ]:
re.findall(r"\D+",text)

['PIN : ']

In [ ]:
re.search(r"\d{3}",text).group()

'789'

In [ ]:
text = "1PIN1 : 7890"

In [ ]:
# 1.
re.search(r'\d{1}',text).group()

'1'

In [ ]:
# 2.
re.search(r'\d{4}',text).group()
# 1178/7890/smth else

'7890'

In [ ]:
# 3.
print(re.search(r'\d{5}',text))

None

In [ ]:
text = "Hello ,World!"

In [ ]:
re.findall(r"\w",text)

['H', 'e', 'l', 'l', 'o', 'W', 'o', 'r', 'l', 'd']

In [ ]:
re.findall(r"\w+",text)
# \w gives us words character

['Hello', 'World']

In [ ]:
re.findall(r"\d",text)
# while d gives nothing because it dosn't contain any digit

[]

In [ ]:
re.findall(r"\W",text)

[' ', ',', '!']

In [ ]:
text = 'ABC123ab_c12'
# fetch all lowercase elements!
re.findall('[a-z]',text)
#it will fetch all lowercases from dataset

['a', 'b', 'c']

In [ ]:
text = 'ABC123ab_c12'
# fetch all uppercase elements!
re.findall('[A-Z]',text)
#it will fetch all UPPERCASE from dataset

['A', 'B', 'C']

In [ ]:
# if we want both

text = 'ABC123ab_c12'
# fetch all lowercase elements!
re.findall('[a-zA-Z]',text)

['A', 'B', 'C', 'a', 'b', 'c']

In [ ]:
text = 'ABC123ab_c12'

In [ ]:
# 1.
re.findall('[a-z]+',text)
#if + written outside the braces it will gives yu a o/p
# whatever the query have but if there is a diff b/w them it also counts like happens in this ab is combine while c is separate and thats why we got two string..

['ab', 'c']

In [ ]:
# 1.
re.findall('[a-z]+',text)
#in uppercase it's not happen because abc are written combine

['ab', 'c']

In [ ]:
# 3.
re.findall('[a-zA-Z]+',text)

['ABC', 'ab', 'c']

QUESTIONS.

In [ ]:
# 1. Find all words in the sentence
# Extract all words (alphanumeric + underscore) from this string:
text = "Welcome_to Regex101! Learn & practice now."
re.findall(r'\w+',text)

['Welcome_to', 'Regex101', 'Learn', 'practice', 'now']

In [ ]:
# 2. Check if a string starts with 'Hi'
text = "Hi there!"
re.findall(r'^Hi',text)

['Hi']

In [ ]:
# 3. Find all digits in the string
text = "Room number 42, Floor 5"
re.findall(r"\d+",text)

['42', '5']

In [ ]:
# 4. Match if string ends with a question mark
text = 'Are you coming?'
re.findall(r"\?$",text)

['?']

In [ ]:
# 5.
text = "My number is 9876543210 and not 98765432101"
# 9876543210 : 10 digit number
# 98765432101 : 11 digit number
# Can you extract the correct mobile number from this?\
re.search(r'\d{10}',text).group()

'9876543210'