In [ ]:
# int float str bool
# list tuples sets dict
# for while if else elif
# function def
# numpy array
"""
# pandas --> Series, DataFrame

# Why Pandas : One of the most important library in python.
# Series : 1d data(single column in an excel file)
# Dataframe : 2d data (multiple columns in an excel file)

"""

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
import pandas as pd

# @title Series
# 1d -> column in an excel file

obj = pd.Series([1,"Masai",2.5,True])

print(obj)

0        1
1    Masai
2      2.5
3     True
dtype: object

In [ ]:
# 1. Tabular structure
# 2. Indexes are automatically added
# 3. overall dtype of the elements in side the Series!

In [ ]:
print(type(obj))

<class 'pandas.core.series.Series'>

In [ ]:
print(obj)

0        1
1    Masai
2      2.5
3     True
dtype: object

In [ ]:
obj[0]

1

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj.values

array([1, 'Masai', 2.5, True], dtype=object)

In [ ]:
type(obj.values)

numpy.ndarray

In [ ]:
score={"Jane":69, "Bill":80,
       "Elon":85,"Tom":75,"Tim":95}

type(score)

names = pd.Series(score)
print(names)

Jane    69
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [ ]:
# names['tom'] # python is case sensitive langauge! it gives error the reason is python is case sensitive.

In [ ]:
print(names['Tom'])

75

In [ ]:
print(names)

Jane    69
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [ ]:
names >= 85
# 1. 5 True or Falses --> CORRECT !!
# 2. Display the name whose score >= 85

Jane    False
Bill    False
Elon     True
Tom     False
Tim      True
dtype: bool

In [ ]:
names[names>=85]

Elon    85
Tim     95
dtype: int64

In [ ]:
# @title  Pandas DataFrames


data = {"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],

        "score":[90,80,85,75,95,60,65],

       "sport":["Wrestling","Football","Skiing","Swimming",
                "Tennis","Karete","Surfing"],

        "gender":["M","M","M","M","F","F","F"]}

data.keys()

dict_keys(['name', 'score', 'sport', 'gender'])

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

# 1. Rows and Columns
# 2. Indexes are automatically added

      name  score      sport gender
0     Bill     90  Wrestling      M
1      Tom     80   Football      M
2      Tim     85     Skiing      M
3     John     75   Swimming      M
4     Alex     95     Tennis      F
5  Vanessa     60     Karete      F
6     Kate     65    Surfing      F

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# name : masai, rekha, rishab, , anushka --> 50000 enteries?
# in pandas : we can directly different type of files as well!

# df = pd.read_csv('path/filename.csv')

df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.head()
# by default : first 5 rows of the data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
df.tail()
# by default : last 5 rows of the data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.shape # rows, columns

(17000, 9)

In [ ]:
df.columns
# column names

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df.dtypes
# every column and its datatype

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
df.describe()
# Stats features of numerical columns

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
longitude,17000.0,-119.562108,2.005166,-124.3500,-121.790000,-118.4900,-118.000,-114.3100
latitude,17000.0,35.625225,2.137340,32.5400,33.930000,34.2500,37.720,41.9500
housing_median_age,17000.0,28.589353,12.586937,1.0000,18.000000,29.0000,37.000,52.0000
total_rooms,17000.0,2643.664412,2179.947071,2.0000,1462.000000,2127.0000,3151.250,37937.0000
total_bedrooms,17000.0,539.410824,421.499452,1.0000,297.000000,434.0000,648.250,6445.0000
population,17000.0,1429.573941,1147.852959,3.0000,790.000000,1167.0000,1721.000,35682.0000
households,17000.0,501.221941,384.520841,1.0000,282.000000,409.0000,605.250,6082.0000
median_income,17000.0,3.883578,1.908157,0.4999,2.566375,3.5446,4.767,15.0001
median_house_value,17000.0,207300.912353,115983.764387,14999.0000,119400.000000,180400.0000,265000.000,500001.0000

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
# Select 1 column
df['total_rooms']

0        5612.0
1        7650.0
2         720.0
3        1501.0
4        1454.0
          ...
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 17000, dtype: float64

In [ ]:
# Select 2 / 2 + columns :

df[['longitude','latitude','population']]

       longitude  latitude  population
0        -114.31     34.19      1015.0
1        -114.47     34.40      1129.0
2        -114.56     33.69       333.0
3        -114.57     33.64       515.0
4        -114.57     33.57       624.0
...          ...       ...         ...
16995    -124.26     40.58       907.0
16996    -124.27     40.69      1194.0
16997    -124.30     41.84      1244.0
16998    -124.30     41.80      1298.0
16999    -124.35     40.54       806.0

[17000 rows x 3 columns]

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df['median_house_value']/10

0         6690.0
1         8010.0
2         8570.0
3         7340.0
4         6550.0
          ...
16995    11140.0
16996     7900.0
16997    10360.0
16998     8580.0
16999     9460.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
df['new_median_values'] = df['median_house_value']/10

df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,11140.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,7900.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10360.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,8580.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9460.0

In [ ]:
# Filter pandas df!

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0

In [ ]:
# Filter data where sales > 20
df['total_bedrooms'] > 1000

0         True
1         True
2        False
3        False
4        False
         ...
16995    False
16996    False
16997    False
16998    False
16999    False
Name: total_bedrooms, Length: 17000, dtype: bool

In [ ]:
# Filter data where sales > 20
df[df['total_bedrooms'] > 1000]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0,5840.0
115,-115.85,34.20,34.0,3868.0,1257.0,890.0,423.0,1.3571,41000.0,4100.0
133,-116.06,34.15,15.0,10377.0,2331.0,4507.0,1807.0,2.2466,66800.0,6680.0
...,...,...,...,...,...,...,...,...,...,...
16824,-123.22,39.28,16.0,5569.0,1106.0,3148.0,1088.0,3.1455,142900.0,14290.0
16838,-123.34,39.10,24.0,5372.0,1051.0,3002.0,992.0,3.0652,131100.0,13110.0
16854,-123.49,38.70,9.0,5409.0,1019.0,594.0,327.0,3.3125,295400.0,29540.0
16859,-123.59,38.80,17.0,5202.0,1037.0,1742.0,803.0,3.1201,176100.0,17610.0
16986,-124.19,40.73,21.0,5694.0,1056.0,2907.0,972.0,3.5363,90100.0,9010.0

In [ ]:
# What if I want to filter on 2 conditions
# i. sales > 20  || ii. radio > 250

# df[(cond1.) & (cond2.)]
df[(df['Sales']>20) & (df['Radio']>25)]

KeyError: 'Sales'

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,11140.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,7900.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10360.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,8580.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9460.0

In [ ]:
df.sort_values(by='longitude') # ascending

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9460.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,8580.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10360.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,7900.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,11140.0
...,...,...,...,...,...,...,...,...,...,...
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0

In [ ]:
df.sort_values(by='longitude', ascending=False) # descending

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,11140.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,7900.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10360.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,8580.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9460.0

In [ ]:
df.head()
# 1. original data --> CORRECT
# 2. ascending sort on sales
# 3. descending sort on sales

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0

In [ ]:
# i) df = df.sort_values(by='Sales', ascending=False)

# using inplace = True
df.sort_values(by='longitude', ascending=False, inplace=True)

df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_median_values
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6690.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,8010.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,8570.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,7340.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,6550.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,11140.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,7900.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10360.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,8580.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9460.0

In [ ]:
# Ques for tomorrow (22 Apr) :
# If indexes are shuffled in a pandas df,
# how can we restore them to their original order?

# series, filterations, head, shape tail, describe, info, sort_values, dataframes

In [ ]:
# @title Question

data = {
    "Name": ["Amit", "Sara", "John", "Neha", "Raj"],
    "Age": [23, 25, 22, 24, 26],
    "Marks": [45, 67, 23, 89, 56],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)

   Name  Age  Marks    City
0  Amit   23     45   Delhi
1  Sara   25     67  Mumbai
2  John   22     23    Pune
3  Neha   24     89   Delhi
4   Raj   26     56  Mumbai

In [ ]:
# Q3
# Show first 3 rows of the DataFrame.

# Q4
# Find total number of rows and columns.

# Q5
# Get all students who scored more than 60.

# Q6
# Find students who are from Delhi.

# Q7
# Add a new column "Passed" where Marks > 50 → True else False.

# Q8
# Increase all marks by 5.

# Q9
# Sort students by Marks in descending order.

# Q10
# Find the average marks of all students.

In [ ]:
# A3
df.head(3)

   Name  Age  Marks    City  Passed
0  Amit   23     50   Delhi   False
1  Sara   25     72  Mumbai    True
2  John   22     28    Pune   False

In [ ]:
# A4
df.shape

(5, 5)

In [ ]:
# A5
df[df["Marks"] > 60]

   Name  Age  Marks    City  Passed
1  Sara   25     72  Mumbai    True
3  Neha   24     94   Delhi    True
4   Raj   26     61  Mumbai    True

In [ ]:
# A6
df[df["City"] == "Delhi"]

   Name  Age  Marks   City  Passed
0  Amit   23     50  Delhi   False
3  Neha   24     94  Delhi    True

In [ ]:
# A7
df["Passed"] = df["Marks"] > 50

In [ ]:
# A8
df["Marks"] = df["Marks"] + 5

In [ ]:


# A9
df.sort_values(by="Marks", ascending=False)

   Name  Age  Marks    City  Passed
3  Neha   24     99   Delhi    True
1  Sara   25     77  Mumbai    True
4   Raj   26     66  Mumbai    True
0  Amit   23     55   Delhi   False
2  John   22     33    Pune   False

In [ ]:

# A10
df["Marks"].mean()

np.float64(66.0)