In [ ]:
# int float str bool
# list tuples sets dict
# for while if else elif
# function def
# numpy array

In [ ]:
# pandas --> Series, DataFrame

In [ ]:
# Why Pandas : One of the most important library in python.
# Series : 1d data(single column in an excel file)
# Dataframe : 2d data (multiple columns in an excel file)

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
# @title Series
# 1d -> column in an excel file

In [ ]:
obj = pd.Series([1,"Masai",2.5,True])

In [ ]:
print(obj)

0        1
1    Masai
2      2.5
3     True
dtype: object

In [ ]:
# 1. Tabular structure
# 2. Indexes are automatically added
# 3. overall dtype of the elements in side the Series!

In [ ]:
print(type(obj))

<class 'pandas.core.series.Series'>

In [ ]:
print(obj)

0        1
1    Masai
2      2.5
3     True
dtype: object

In [ ]:
obj[0]

1

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(obj)

0        1
1    Masai
2      2.5
3     True
dtype: object

In [ ]:
obj.values

array([1, 'Masai', 2.5, True], dtype=object)

In [ ]:
type(obj.values)

numpy.ndarray

In [ ]:
score={"Jane":69, "Bill":80,
       "Elon":85,"Tom":75,"Tim":95}

type(score)

dict

In [ ]:
names = pd.Series(score)
print(names)

Jane    85
Bill    80
Tom     75
Tim     95
dtype: int64

In [ ]:
names['tom'] # python is case sensitive langauge!

KeyError: 'tom'

In [ ]:
print(names['Tom'])

75

In [ ]:
print(names)

Jane    69
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [ ]:
names >= 85
# 1. 5 True or Falses --> CORRECT !!
# 2. Display the name whose score >= 85

Jane    False
Bill    False
Elon     True
Tom     False
Tim      True
dtype: bool

In [ ]:
names[names>=85]

Elon    85
Tim     95
dtype: int64

In [ ]:
# @title  Pandas DataFrames

In [ ]:
data = {"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],

        "score":[90,80,85,75,95,60,65],

       "sport":["Wrestling","Football","Skiing","Swimming",
                "Tennis","Karete","Surfing"],

        "gender":["M","M","M","M","F","F","F"]}

In [ ]:
data.keys()

dict_keys(['name', 'score', 'sport', 'gender'])

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

      name  score      sport gender
0     Bill     90  Wrestling      M
1      Tom     80   Football      M
2      Tim     85     Skiing      M
3     John     75   Swimming      M
4     Alex     95     Tennis      F
5  Vanessa     60     Karete      F
6     Kate     65    Surfing      F

In [ ]:
# 1. Rows and Columns
# 2. Indexes are automatically added

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# name : masai, rekha, rishab, , anushka --> 50000 enteries?
# in pandas : we can directly different type of files as well!

In [ ]:
# df = pd.read_csv('path/filename.csv')

In [ ]:
df = pd.read_csv('/content/advertising.csv')

In [ ]:
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
df.head()
# by default : first 5 rows of the data

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [ ]:
df.tail()
# by default : last 5 rows of the data

        TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [ ]:
df.shape # rows, columns

(200, 4)

In [ ]:
df.columns
# column names

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [ ]:
df.dtypes
# every column and its datatype

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [ ]:
df.describe()
# Stats features of numerical columns

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
df.describe().T

           count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
Radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
Newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
Sales      200.0   15.1305   5.283892  1.6  11.000   16.00   19.050   27.0

In [ ]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [ ]:
# Select 1 column
df['TV']

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [ ]:
# Select 2 / 2 + columns :

In [ ]:
df[['TV','Sales','Newspaper']]

        TV  Sales  Newspaper
0    230.1   22.1       69.2
1     44.5   10.4       45.1
2     17.2   12.0       69.3
3    151.5   16.5       58.5
4    180.8   17.9       58.4
..     ...    ...        ...
195   38.2    7.6       13.8
196   94.2   14.0        8.1
197  177.0   14.8        6.4
198  283.6   25.5       66.2
199  232.1   18.4        8.7

[200 rows x 3 columns]

In [ ]:
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
df['Sales']/10

0      2.21
1      1.04
2      1.20
3      1.65
4      1.79
       ...
195    0.76
196    1.40
197    1.48
198    2.55
199    1.84
Name: Sales, Length: 200, dtype: float64

In [ ]:
df['new_sales'] = df['Sales']/10

In [ ]:
df

        TV  Radio  Newspaper  Sales  new_sales
0    230.1   37.8       69.2   22.1       2.21
1     44.5   39.3       45.1   10.4       1.04
2     17.2   45.9       69.3   12.0       1.20
3    151.5   41.3       58.5   16.5       1.65
4    180.8   10.8       58.4   17.9       1.79
..     ...    ...        ...    ...        ...
195   38.2    3.7       13.8    7.6       0.76
196   94.2    4.9        8.1   14.0       1.40
197  177.0    9.3        6.4   14.8       1.48
198  283.6   42.0       66.2   25.5       2.55
199  232.1    8.6        8.7   18.4       1.84

[200 rows x 5 columns]

In [ ]:
# Filter pandas df!

In [ ]:
df.head()

      TV  Radio  Newspaper  Sales  new_sales
0  230.1   37.8       69.2   22.1       2.21
1   44.5   39.3       45.1   10.4       1.04
2   17.2   45.9       69.3   12.0       1.20
3  151.5   41.3       58.5   16.5       1.65
4  180.8   10.8       58.4   17.9       1.79

In [ ]:
# Filter data where sales > 20
df['Sales'] > 30

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: Sales, Length: 200, dtype: bool

In [ ]:
# Filter data where sales > 20
df[df['Sales'] > 20]

        TV  Radio  Newspaper  Sales  new_sales
0    230.1   37.8       69.2   22.1       2.21
15   195.4   47.7       52.9   22.4       2.24
17   281.4   39.6       55.8   24.4       2.44
23   228.3   16.9       26.2   20.5       2.05
27   240.1   16.7       22.9   20.9       2.09
30   292.9   28.3       43.2   21.4       2.14
36   266.9   43.8        5.0   25.4       2.54
39   228.0   37.7       32.0   21.5       2.15
42   293.6   27.7        1.8   20.7       2.07
47   239.9   41.5       18.5   23.2       2.32
52   216.4   41.7       39.6   22.6       2.26
53   182.6   46.2       58.7   21.2       2.12
54   262.7   28.8       15.9   20.2       2.02
55   198.9   49.4       60.0   23.7       2.37
58   210.8   49.6       37.7   23.8       2.38
61   261.3   42.7       54.7   24.2       2.42
62   239.3   15.5       27.3   20.7       2.07
69   216.8   43.9       27.2   22.3       2.23
84   213.5   43.0       33.8   21.7       2.17
85   193.2   18.4       65.7   20.2       2.02
93   250.9   36.5       72.3   22.2       2.22
97   184.9   21.0       22.0   20.5       2.05
98   289.7   42.3       51.2   25.4       2.54
101  296.4   36.3      100.9   23.8       2.38
104  238.2   34.3        5.3   20.7       2.07
111  241.7   38.0       23.2   21.8       2.18
113  209.6   20.6       10.7   20.9       2.09
128  220.3   49.0        3.2   24.7       2.47
137  273.7   28.9       59.7   20.8       2.08
139  184.9   43.9        1.7   20.7       2.07
142  220.5   33.2       37.9   20.1       2.01
147  243.2   49.0       44.3   25.4       2.54
154  187.8   21.1        9.5   20.6       2.06
175  276.9   48.9       41.8   27.0       2.70
176  248.4   30.2       20.3   20.2       2.02
183  287.6   43.0       71.8   26.2       2.62
185  205.0   45.1       19.6   22.6       2.26
188  286.0   13.9        3.7   20.9       2.09
198  283.6   42.0       66.2   25.5       2.55

In [ ]:
# What if I want to filter on 2 conditions
# i. sales > 20  || ii. radio > 250

In [ ]:
# df[(cond1.) & (cond2.)]
df[(df['Sales']>20) & (df['Radio']>250)]

Empty DataFrame
Columns: [TV, Radio, Newspaper, Sales, new_sales]
Index: []

In [ ]:
df

        TV  Radio  Newspaper  Sales  new_sales
0    230.1   37.8       69.2   22.1       2.21
1     44.5   39.3       45.1   10.4       1.04
2     17.2   45.9       69.3   12.0       1.20
3    151.5   41.3       58.5   16.5       1.65
4    180.8   10.8       58.4   17.9       1.79
..     ...    ...        ...    ...        ...
195   38.2    3.7       13.8    7.6       0.76
196   94.2    4.9        8.1   14.0       1.40
197  177.0    9.3        6.4   14.8       1.48
198  283.6   42.0       66.2   25.5       2.55
199  232.1    8.6        8.7   18.4       1.84

[200 rows x 5 columns]

In [ ]:
df.sort_values(by='Sales') # ascending

        TV  Radio  Newspaper  Sales  new_sales
130    0.7   39.6        8.7    1.6       0.16
155    4.1   11.6        5.7    3.2       0.32
8      8.6    2.1        1.0    4.8       0.48
78     5.4   29.9        9.4    5.3       0.53
108   13.1    0.4       25.6    5.3       0.53
..     ...    ...        ...    ...        ...
36   266.9   43.8        5.0   25.4       2.54
147  243.2   49.0       44.3   25.4       2.54
198  283.6   42.0       66.2   25.5       2.55
183  287.6   43.0       71.8   26.2       2.62
175  276.9   48.9       41.8   27.0       2.70

[200 rows x 5 columns]

In [ ]:
df.sort_values(by='Sales', ascending=False) # descending

        TV  Radio  Newspaper  Sales  new_sales
175  276.9   48.9       41.8   27.0       2.70
183  287.6   43.0       71.8   26.2       2.62
198  283.6   42.0       66.2   25.5       2.55
36   266.9   43.8        5.0   25.4       2.54
98   289.7   42.3       51.2   25.4       2.54
..     ...    ...        ...    ...        ...
78     5.4   29.9        9.4    5.3       0.53
108   13.1    0.4       25.6    5.3       0.53
8      8.6    2.1        1.0    4.8       0.48
155    4.1   11.6        5.7    3.2       0.32
130    0.7   39.6        8.7    1.6       0.16

[200 rows x 5 columns]

In [ ]:
df.head()
# 1. original data --> CORRECT
# 2. ascending sort on sales
# 3. descending sort on sales

      TV  Radio  Newspaper  Sales  new_sales
0  230.1   37.8       69.2   22.1       2.21
1   44.5   39.3       45.1   10.4       1.04
2   17.2   45.9       69.3   12.0       1.20
3  151.5   41.3       58.5   16.5       1.65
4  180.8   10.8       58.4   17.9       1.79

In [ ]:
# i) df = df.sort_values(by='Sales', ascending=False)

In [ ]:
# using inplace = True
df.sort_values(by='Sales', ascending=False, inplace=True)

In [ ]:
df

        TV  Radio  Newspaper  Sales  new_sales
175  276.9   48.9       41.8   27.0       2.70
183  287.6   43.0       71.8   26.2       2.62
198  283.6   42.0       66.2   25.5       2.55
36   266.9   43.8        5.0   25.4       2.54
98   289.7   42.3       51.2   25.4       2.54
..     ...    ...        ...    ...        ...
78     5.4   29.9        9.4    5.3       0.53
108   13.1    0.4       25.6    5.3       0.53
8      8.6    2.1        1.0    4.8       0.48
155    4.1   11.6        5.7    3.2       0.32
130    0.7   39.6        8.7    1.6       0.16

[200 rows x 5 columns]

In [ ]:
# Ques for tomorrow (22 Apr) :
# If indexes are shuffled in a pandas df,
# how can we restore them to their original order?

In [ ]:
# series, filterations, head, shape tail, describe, info, sort_values, dataframes

In [ ]:
# @title Question

In [ ]:
data = {
    "Name": ["Amit", "Sara", "John", "Neha", "Raj"],
    "Age": [23, 25, 22, 24, 26],
    "Marks": [45, 67, 23, 89, 56],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)

   Name  Age  Marks    City
0  Amit   23     45   Delhi
1  Sara   25     67  Mumbai
2  John   22     23    Pune
3  Neha   24     89   Delhi
4   Raj   26     56  Mumbai

In [ ]:
# Q3
# Show first 3 rows of the DataFrame.

# Q4
# Find total number of rows and columns.

# Q5
# Get all students who scored more than 60.

# Q6
# Find students who are from Delhi.

# Q7
# Add a new column "Passed" where Marks > 50 → True else False.

# Q8
# Increase all marks by 5.

# Q9
# Sort students by Marks in descending order.

# Q10
# Find the average marks of all students.

In [ ]:
# A3
# df.head(3)

# A4
# df.shape

# A5
# df[df["Marks"] > 60]

# A6
# df[df["City"] == "Delhi"]

# A7
# df["Passed"] = df["Marks"] > 50

# A8
# df["Marks"] = df["Marks"] + 5

# A9
# df.sort_values(by="Marks", ascending=False)

# A10
# df["Marks"].mean()