In [ ]:
# Excel : https://docs.google.com/spreadsheets/d/1JkYP6PC4_wiI2nRvN2y8qiVeRIOgs9GwnUOjDFovYpo/edit?usp=sharing

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
data1 = {
    'id': [1, 2],
    'name': ['Ajay', 'Drishan']
}
df1 = pd.DataFrame(data1)

In [ ]:
data2 = {
    'id': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df2 = pd.DataFrame(data2)

In [ ]:
df1

   id     name
0   1     Ajay
1   2  Drishan

In [ ]:
df2

   id       dept
0   1  Analytics
1   3       Tech

In [ ]:
pd.merge(df1, df2, how = 'inner', on = 'id')

   id  name       dept
0   1  Ajay  Analytics

In [ ]:
pd.merge(df1, df2, how = 'left', on = 'id')

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN

In [ ]:
pd.merge(df1, df2, how = 'right', on = 'id')

   id  name       dept
0   1  Ajay  Analytics
1   3   NaN       Tech

In [ ]:
pd.merge(df1, df2, how = 'outer', on = 'id')

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN
2   3      NaN       Tech

In [ ]:
data1 = {
    'id1': [1, 2],
    'name': ['Ajay', 'Drishan']
}
df1 = pd.DataFrame(data1)

In [ ]:
data2 = {
    'id2': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df2 = pd.DataFrame(data2)

In [ ]:
df1

   id1     name
0    1     Ajay
1    2  Drishan

In [ ]:
df2

   id2       dept
0    1  Analytics
1    3       Tech

In [ ]:
# pd.merge(df1,df2,how='inner',on='id') # error

In [ ]:
pd.merge(df1, df2, how = 'inner', left_on = 'id1', right_on = 'id2')

   id1  name  id2       dept
0    1  Ajay    1  Analytics

In [ ]:
pd.merge(df1, df2, how = 'inner', left_on = 'id1', right_on = 'id2')

   id1  name  id2       dept
0    1  Ajay    1  Analytics

In [ ]:
# Customers DataFrame
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "order_id": ["A", "B", "C", "D"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai"]
})

# Orders DataFrame
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 2, 3, 5],
    "amount": [500, 300, 200, 700]
})

print(df_customers)
print('-'*32)
print(df_orders)

   customer_id order_id       city
0            1        A  Bangalore
1            2        B      Delhi
2            3        C     Mumbai
3            4        D    Chennai
--------------------------------
   order_id  customer_id  amount
0       101            1     500
1       102            2     300
2       103            3     200
3       104            5     700

In [ ]:
pd.merge(df_customers,df_orders, how='inner',on='customer_id')

   customer_id order_id_x       city  order_id_y  amount
0            1          A  Bangalore         101     500
1            2          B      Delhi         102     300
2            3          C     Mumbai         103     200

In [ ]:
pd.merge(df_customers,df_orders, how='inner',on='customer_id',
         suffixes=('_left','_right'))

   customer_id order_id_left       city  order_id_right  amount
0            1             A  Bangalore             101     500
1            2             B      Delhi             102     300
2            3             C     Mumbai             103     200

In [ ]:
# T3: colors
t3 = pd.DataFrame({
    "colors": ["red", "blue"]
})

# T4: sizes
t4 = pd.DataFrame({
    "sizes": ["S", "M", "L", "XL"]
})

print(t3)
print('-'*32)
print(t4)

  colors
0    red
1   blue
--------------------------------
  sizes
0     S
1     M
2     L
3    XL

In [ ]:
pd.merge(t3,t4,how='cross')

  colors sizes
0    red     S
1    red     M
2    red     L
3    red    XL
4   blue     S
5   blue     M
6   blue     L
7   blue    XL

In [ ]:
df1=pd.DataFrame(
    {"letter":["a","b","c"],
     "num":range(3)})
df2=pd.DataFrame(
    {"value":[3,5,7]},
    index=["a","b","e"])

In [ ]:
df1

  letter  num
0      a    0
1      b    1
2      c    2

In [ ]:
df2

   value
a      3
b      5
e      7

In [ ]:
# col - index join as well!

In [ ]:
pd.merge(df1,df2,how='inner',left_on = 'letter',right_index=True)

  letter  num  value
0      a    0      3
1      b    1      5

In [ ]:
# index - index
# left_index = True,right_index=True

In [ ]:
df1 = pd.DataFrame({
    "name": ["A", "B", "C"],
    "score": [80, 85, 90]
})

df2 = pd.DataFrame({
    "name": ["D", "E"],
    "score": [70, 75]
})

print(df1)
print('-'*32)
print(df2)

  name  score
0    A     80
1    B     85
2    C     90
--------------------------------
  name  score
0    D     70
1    E     75

In [ ]:
# Row-wise
pd.concat([df1,df2], axis = 0)

  name  score
0    A     80
1    B     85
2    C     90
0    D     70
1    E     75

In [ ]:
pd.concat([df1,df2], axis = 0,ignore_index=True)

  name  score
0    A     80
1    B     85
2    C     90
3    D     70
4    E     75

In [ ]:
pd.concat([df1,df2], axis = 1)
# can add - ignore_index=True

  name  score name  score
0    A     80    D   70.0
1    B     85    E   75.0
2    C     90  NaN    NaN